const DEBUG = Boolean(process.env.DEBUG);

const SERVICE_ACCOUNT_JSON = JSON.parse(process.env.SERVICE_ACCOUNT_KEY);

const BIGQUERY_DATASET_ID = process.env.BG_DATASET_ID;
const BIGQUERY_TABLE_USERS_ID = process.env.BG_USERS_ID;
const BIGQUERY_TABLE_ORGANIZATIONS_ID = process.env.BG_ORGS_ID;
const BIGQUERY_TABLE_PRACTICES_ID = process.env.BG_UNITS_ID;
const BIGQUERY_TABLE_CASE_CARDS_ID = process.env.BG_CASE_CARDS_ID;
const BIGQUERY_TABLE_CASE_CARDS_TRANS_LOG_ID = process.env.BG_CASE_CARDS_TRANS_LOG_ID;
const BIGQUERY_TABLE_TENANT_CONFIG_ID = process.env.BG_TENANT_CONFIG_ID;

const BIGQUERY_TABLE_USER_ROLES_ID = process.env.BG_USER_ROLES_ID;
const BIGQUERY_TABLE_ROLES_ID = process.env.BG_ROLES_ID;

const BIGQUERY_TABLE_PATIENTS_LINK_ID = process.env.BG_PATIENTS_LINK_ID;
const BIGQUERY_TABLE_CASE_CARD_LINK_ID = process.env.BG_CASE_CARD_LINK_ID;
const BIGQUERY_TABLE_ROLE_LINK_ID = process.env.BG_ROLE_LINK_ID;
const BIGQUERY_TABLE_USER_LINK_ID = process.env.BG_USER_LINK_ID;

module.exports = {
  DEBUG,

  SERVICE_ACCOUNT_JSON,

  BIGQUERY_DATASET_ID,
  BIGQUERY_TABLE_USERS_ID,
  BIGQUERY_TABLE_ORGANIZATIONS_ID,
  BIGQUERY_TABLE_PRACTICES_ID,
  BIGQUERY_TABLE_CASE_CARDS_ID,
  BIGQUERY_TABLE_CASE_CARDS_TRANS_LOG_ID,
  BIGQUERY_TABLE_TENANT_CONFIG_ID,

  BIGQUERY_TABLE_USER_ROLES_ID,
  BIGQUERY_TABLE_ROLES_ID,

  BIGQUERY_TABLE_PATIENTS_LINK_ID,
  BIGQUERY_TABLE_CASE_CARD_LINK_ID,
  BIGQUERY_TABLE_ROLE_LINK_ID,
  BIGQUERY_TABLE_USER_LINK_ID,
};
