---
include:
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.74/docker-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.74/static-analysis.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.74/license-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.74/terraform-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.74/git-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.74/gitlab-toolkit.yml"


stages:
  - test
  - build
  - push

variables:
  DOCKER_DRIVER: "overlay2"
  DOCKER_TLS_CERTDIR: "/certs"


build:
  extends: .build-multiarch
  stage: build
  variables:
    PLATFORMS: linux/amd64
  needs: [ ]

push:
  extends: .gitlab-dockerhub-push
  stage: push
  environment:
    name: prod
  variables:
    DOCKER_IMAGE_DESTINATION: "miquido/dynamic-environments:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"
    DOCKER_IMAGE_SECONDARY_DESTINATION: "miquido/dynamic-environments:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual


get-latest-terraform:
  extends: .get-latest-terraform

check-formatting:
  extends: .check-formatting

validate:
  extends: .validate-terraform
  variables:
    ENVIRONMENTS: examples/complete

bump-tag:
  extends: .bump_minor_tag

docs:
  extends: .generate_readme
  stage: .post

push_readme:
  extends: .push_readme
  stage: .post
  dependencies: [ "docs" ]
  needs: [ "docs" ]

